# Generated by Django 4.2.1 on 2023-06-03 08:13

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("movies", "0002_movie_rating"),
    ]

    operations = [
        migrations.CreateModel(
            name="Director",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("first_name", models.CharField(max_length=100, verbose_name="imię")),
                (
                    "last_name",
                    models.CharField(max_length=100, verbose_name="nazwisko"),
                ),
                ("about", models.TextField(blank=True, verbose_name="opis")),
            ],
        ),
    ]
