# Generated by Django 4.2.1 on 2023-06-03 08:41

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('movies', '0003_director'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='director',
            options={'verbose_name': 'reżyser', 'verbose_name_plural': 'reżyserzy'},
        ),
        migrations.AlterModelOptions(
            name='movie',
            options={'verbose_name': 'film', 'verbose_name_plural': 'filmy'},
        ),
        migrations.AddField(
            model_name='movie',
            name='director',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, related_name='movies', to='movies.director', verbose_name='reżyser'),
        ),
    ]
